version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: react-native-webview
    versions:
    - 11.2.0
    - 11.2.1
    - 11.2.3
    - 11.3.1
    - 11.3.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: react-native-svg
    versions:
    - 12.1.0
